# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = "research/"
  weight = 20
  
[[main]]
  name = "Publication"
  url = "publication/"
  weight = 30

[[main]]
  name = "Resources"
  url = "resources/"
  weight = 40
  identifier = "resources"
  
[[main]]
  name = "Forced Alignment"
  url = "resources/1forcedalignment"
  weight = 10
  parent = "resources"
[[main]]
  name = "Speech Corpus Querying"
  url = "resources/2speechcorpus"
  weight = 20
  parent = "resources"
[[main]]
  name = "ASR in Linguistic Research"
  url = "resources/3asr"
  weight = 30
  parent = "resources"
[[main]]
  name = "Research Hacks"
  url = "resources/4researchskill"
  weight = 40
  parent = "resources"

[[main]]
  name = "Teaching"
  url = "#talks"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
